#!/usr/bin/env node
// Build the whole game into ONE self-contained HTML file that plays offline:
// no server, no internet, no install. Copy it to a phone or laptop and open it.
//
//   node tools/build.js            writes offline/StoryWord.html
//   node tools/build.js --check    exits 1 if offline/StoryWord.html is stale
//
// It inlines the stylesheet, bundles the ES modules (they only use the plain
// `import ... from './x.js'` / `export function|const` forms), and embeds all
// content JSON as window.STORYWORD_CONTENT.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative, resolve } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export const OUTPUT = join(root, 'offline', 'StoryWord.html');

async function bundle(entry) {
  const order = [];
  const seen = new Set();
  const sources = new Map();
  async function visit(file) {
    if (seen.has(file)) return;
    seen.add(file);
    const code = await readFile(file, 'utf8');
    sources.set(file, code);
    for (const m of code.matchAll(/^import [^'"]+ from '(\.[^']+)';$/gm)) {
      await visit(resolve(dirname(file), m[1]));
    }
    order.push(file);
  }
  await visit(entry);

  const key = (f) => relative(root, f);
  return order
    .map((file) => {
      const exported = [];
      let code = sources.get(file);
      code = code.replace(/^import \* as (\w+) from '(\.[^']+)';$/gm, (_, name, p) => `const ${name} = __mod[${JSON.stringify(key(resolve(dirname(file), p)))}];`);
      code = code.replace(/^import \{([^}]+)\} from '(\.[^']+)';$/gm, (_, names, p) => `const {${names}} = __mod[${JSON.stringify(key(resolve(dirname(file), p)))}];`);
      code = code.replace(/^export (async function|function|const|let) (\w+)/gm, (_, kind, name) => {
        exported.push(name);
        return `${kind} ${name}`;
      });
      if (/^\s*(import|export)\s/m.test(code)) throw new Error(`${key(file)}: unsupported import/export form`);
      return `__mod[${JSON.stringify(key(file))}] = (() => {\n${code}\nreturn { ${exported.join(', ')} };\n})();`;
    })
    .join('\n');
}

async function content() {
  const read = async (f) => JSON.parse(await readFile(join(root, 'content', f), 'utf8'));
  const story = await read('story.json');
  const files = ['story.json', 'characters.json', 'puzzles.json', 'daily.json', ...story.chapters.map((c) => c.file)];
  const out = {};
  for (const f of files) out[f] = await read(f);
  return out;
}

export async function build() {
  const css = await readFile(join(root, 'styles.css'), 'utf8');
  const icon = await readFile(join(root, 'icon.svg'), 'utf8');
  const js = await bundle(join(root, 'src', 'main.js'));
  const data = JSON.stringify(await content()).replace(/</g, '\\u003c');
  const iconUri = `data:image/svg+xml,${encodeURIComponent(icon)}`;
  return `<!doctype html>
<!-- StoryWord: Crown of the Confluence. Single-file offline build: open this file in any browser. Generated by tools/build.js; do not edit. -->
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<meta name="theme-color" content="#2a0f3a" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<title>StoryWord</title>
<link rel="icon" href="${iconUri}" />
<link rel="apple-touch-icon" href="${iconUri}" />
<style>
${css}
</style>
</head>
<body data-scene="none">
<div id="scene" aria-hidden="true"></div>
<div id="fx" aria-hidden="true"></div>
<div id="app" aria-live="polite"><main class="screen center"><p class="muted">Loading…</p></main></div>
<div id="toasts" aria-live="polite"></div>
<script>
window.STORYWORD_CONTENT = ${data};
</script>
<script>
"use strict";
(() => {
const __mod = {};
${js}
})();
</script>
</body>
</html>
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const html = await build();
  if (process.argv.includes('--check')) {
    const current = await readFile(OUTPUT, 'utf8').catch(() => '');
    if (current !== html) {
      console.error('✗ offline/StoryWord.html is out of date. Run: npm run build');
      process.exit(1);
    }
    console.log('✓ offline build is up to date');
  } else {
    await mkdir(dirname(OUTPUT), { recursive: true });
    await writeFile(OUTPUT, html);
    console.log(`✓ wrote ${relative(process.cwd(), OUTPUT)} (${(html.length / 1024).toFixed(0)} KB)`);
  }
}
